# syntax=docker/dockerfile:1

FROM golang:1.23-alpine AS builder

RUN apk add --no-cache make

WORKDIR /app

ARG BINARY
ARG DATA_PATH

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN make build-${BINARY}

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/bin/${BINARY} .
COPY ${DATA_PATH} /app/data

CMD ["/app/fetcher"]