version: "2"
sql:
  - engine: "postgresql"
    queries: "../internal/app/repository/psql/db/queries/query.sql"
    schema: "../internal/app/repository/migrations/files/"
    gen:
      go:
        package: "db"
        sql_package: "pgx/v5"
        out: "../internal/app/repository/psql/db/sqlc_gen"
        emit_json_tags: true
        emit_prepared_queries: false
        emit_interface: false
        emit_exact_table_names: false
        emit_empty_slices: true
        emit_exported_queries: true
